apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-microservice-deployment
  namespace: postgres-operator
  labels:
    app: calendar-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-microservice
  template:
    metadata:
      labels:
        app: calendar-microservice 
    spec:
      containers:
      - name: calendar-microservice
        image: juliepetrova/calendar-microservice:latest
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "200m"
        imagePullPolicy: Always
        # command: [ 'npx', 'prisma', 'migrate', 'deploy'  ]
        ports:
        - containerPort: 3001
        env: 
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: calendar-postgres-pguser-calendar-postgres
              key: user
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: calendar-postgres-pguser-calendar-postgres
              key: host
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: calendar-postgres-pguser-calendar-postgres
              key: port
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: calendar-postgres-pguser-calendar-postgres
              key: dbname
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: calendar-postgres-pguser-calendar-postgres
              key: uri
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: calendar-postgres-pguser-calendar-postgres
              key: password
        - name: RABBITMQ_CONN_URL
          valueFrom: 
            secretKeyRef:
              name: gss-secret
              key: RABBITMQ_CONN_URL
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-microservice-service
spec:
  type: ClusterIP
  selector:
    app: calendar-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001

