apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodapi-microservice-deployment
  namespace: postgres-operator
  labels:
    app: foodapi-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodapi-microservice
  template:
    metadata:
      labels:
        app: foodapi-microservice 
    spec:
      containers:
      - name: foodapi-microservice
        image: juliepetrova/food-microservice:latest
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "200m"
        imagePullPolicy: Always
        ports:
        - containerPort: 3006
        env: 
        - name: APP_KEY
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: food-app-key
        - name: APP_ID
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: food-app-id
---
apiVersion: v1
kind: Service
metadata:
  name: foodapi-microservice-service
spec:
  type: ClusterIP
  selector:
    app: foodapi-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006

