apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-microservice-deployment
  labels:
    app: calendar-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-microservice
  template:
    metadata:
      labels:
        app: calendar-microservice 
    spec:
      containers:
      - name: calendar-microservice
        image: juliepetrova/calendar-microservice:latest
        imagePullPolicy: Always
        # command: [ 'npx', 'prisma', 'migrate', 'deploy'  ]
        ports:
        - containerPort: 3001
        env: 
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: prisma-username
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: prisma-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: gss-config
              key: calendar-db-url
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: gss-secret
              key: calendar-database-url
        - name: RABBITMQ_CONN_URL
          valueFrom: 
            secretKeyRef:
              name: gss-secret
              key: RABBITMQ_CONN_URL
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-microservice-service
spec:
  type: ClusterIP
  selector:
    app: calendar-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001

