apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-microservice-deployment
  labels:
    app: events-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: events-microservice
  template:
    metadata:
      labels:
        app: events-microservice 
    spec:
      containers:
      - name: events-microservice
        image: juliepetrova/events-microservice:latest
        # command: [ 'npx', 'prisma', 'migrate', 'deploy' ]
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        env: 
        - name: POSTGRES_USER
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: prisma-username
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: prisma-password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: gss-config
              key: events-db-url
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef:
              name: gss-secret
              key: events-database-url
---
apiVersion: v1
kind: Service
metadata:
  name: events-microservice-service
spec:
  type: ClusterIP
  selector:
    app: events-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
