apiVersion: v1
kind: Secret
metadata:
  name: gss-secret
type: Opaque
data:
  prisma-username: anVsaWU=
  prisma-password: cHJpc21hcGFzc3dvcmQ=

  activities-database-url: cG9zdGdyZXNxbDovL2p1bGllOnByaXNtYXBhc3N3b3JkQGFjdGl2aXRpZXMtcHJpc21hLXNlcnZpY2U6NTQzMi9hY3Rpdml0aWVzX2RiP3NjaGVtYT1hY3Rpdml0aWVzJnNzbG1vZGU9cHJlZmVyP2Nvbm5lY3RfdGltZW91dD0zMDA=
  calendar-database-url: cG9zdGdyZXNxbDovL2p1bGllOnByaXNtYXBhc3N3b3JkQGNhbGVuZGFyLXByaXNtYS1zZXJ2aWNlOjU0MzIvY2FsZW5kYXJfZGI/c2NoZW1hPWNhbGVuZGFyJnNzbG1vZGU9cHJlZmVyP2Nvbm5lY3RfdGltZW91dD0zMDA=
  events-database-url: cG9zdGdyZXNxbDovL2p1bGllOnByaXNtYXBhc3N3b3JkQGV2ZW50cy1wcmlzbWEtc2VydmljZTo1NDMyL2V2ZW50c19kYj9zY2hlbWE9ZXZlbnRzX2RiJnNzbG1vZGU9cHJlZmVyP2Nvbm5lY3RfdGltZW91dD0zMDA=

  food-app-key: NTIzZjNmYjIzNDI3NDNlMzIxNTc2Njc5NjZmZTI0NTElMDk=
  food-app-id: ZDY5MTI0YzQ=

  FIREBASE_API_KEY: IkFJemFTeUJ6THplLUlqLUpSVmozYU9mcHRCTVF3U1hVZmc5TmxQWSI=
  FIREBASE_AUTH_DOMAIN: InNlbWVzdGVyNmF1dGguZmlyZWJhc2VhcHAuY29tIg==
  FIREBASE_PROJECT_ID: c2VtZXN0ZXI2YXV0aA==
  FIREBASE_STORAGE_BUCKET: InNlbWVzdGVyNmF1dGguYXBwc3BvdC5jb20i
  FIREBASE_MESSAGING_SENDER_ID: IjgzMzEzNzk0Mzg2NCI=
  FIREBASE_APP_ID: IjE6ODMzMTM3OTQzODY0OndlYjo2NjllYWM0ZTMyMDgwZTg0OWFjZGNkIg==
  FIREBASE_MEASUREMENT_ID: IkctNVdZTjQzVFY4TSI=
  # RABBITMQ_ERLANG_COOKIE: V0lXVkhDRFRDSVVBV0FOTE1RQVc=
