apiVersion: v1
kind: Secret
metadata:
  name: gss-secret
  namespace: postgres-operator
type: Opaque
data:
  food-app-key: NTIzZjNmYjIzNDI3NDNlMzIxNTc2Njc5NjZmZTI0NTElMDk=
  food-app-id: ZDY5MTI0YzQ=

  FIREBASE_API_KEY: IkFJemFTeUJ6THplLUlqLUpSVmozYU9mcHRCTVF3U1hVZmc5TmxQWSI=
  FIREBASE_AUTH_DOMAIN: InNlbWVzdGVyNmF1dGguZmlyZWJhc2VhcHAuY29tIg==
  FIREBASE_PROJECT_ID: c2VtZXN0ZXI2YXV0aA==
  FIREBASE_STORAGE_BUCKET: InNlbWVzdGVyNmF1dGguYXBwc3BvdC5jb20i
  FIREBASE_MESSAGING_SENDER_ID: IjgzMzEzNzk0Mzg2NCI=
  FIREBASE_APP_ID: IjE6ODMzMTM3OTQzODY0OndlYjo2NjllYWM0ZTMyMDgwZTg0OWFjZGNkIg==
  FIREBASE_MEASUREMENT_ID: IkctNVdZTjQzVFY4TSI=

  RABBITMQ_CONN_URL: YW1xcHM6Ly9kd3pvdWVvdTpXOFpkOUxqRGQzN0xXLXFPSU1GSi1KVmhDa1NDZlBJWUByYXR0bGVzbmFrZS5ybXEuY2xvdWRhbXFwLmNvbS9kd3pvdWVvdQ==
  # RABBITMQ_ERLANG_COOKIE: V0lXVkhDRFRDSVVBV0FOTE1RQVc=
