apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  labels:
   type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
