apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
  labels:
    app: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice
  template:
    metadata:
      labels:
        app: user-microservice 
    spec:
      containers:
      - name: user-microservice
        image: juliepetrova/user-microservice:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3007
        env: 
        - name: API_KEY
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: FIREBASE_API_KEY 
        - name: AUTH_DOMAIN
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: FIREBASE_AUTH_DOMAIN 
        - name: PROJECT_ID
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: FIREBASE_PROJECT_ID 
        - name: STORAGE_BUCKET
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: FIREBASE_STORAGE_BUCKET 
        - name: MESSAGING_SENDER_ID
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: FIREBASE_MESSAGING_SENDER_ID 
        - name: APP_ID
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: FIREBASE_APP_ID 
        - name: MEASUREMENT_ID
          valueFrom: 
            secretKeyRef: 
              name: gss-secret
              key: FIREBASE_MEASUREMENT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice-service
spec:
  type: ClusterIP
  selector:
    app: user-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3007

